//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniManage.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbunimanageEntities : DbContext
    {
        public dbunimanageEntities()
            : base("name=dbunimanageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblAssignment> tblAssignments { get; set; }
        public virtual DbSet<tblAssignmentSubmission> tblAssignmentSubmissions { get; set; }
        public virtual DbSet<tblContactMessage> tblContactMessages { get; set; }
        public virtual DbSet<tblCourse> tblCourses { get; set; }
        public virtual DbSet<tblCourseCategory> tblCourseCategories { get; set; }
        public virtual DbSet<tblCourseMaterial> tblCourseMaterials { get; set; }
        public virtual DbSet<tblEnrollment> tblEnrollments { get; set; }
        public virtual DbSet<tblGrade> tblGrades { get; set; }
        public virtual DbSet<tblMessage> tblMessages { get; set; }
        public virtual DbSet<tblMessageNotification> tblMessageNotifications { get; set; }
        public virtual DbSet<tblOtpToken> tblOtpTokens { get; set; }
        public virtual DbSet<tblPayment> tblPayments { get; set; }
        public virtual DbSet<tblRoleClaim> tblRoleClaims { get; set; }
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<tblSystemUsageLog> tblSystemUsageLogs { get; set; }
        public virtual DbSet<tblUserClaim> tblUserClaims { get; set; }
        public virtual DbSet<tblUserLogin> tblUserLogins { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblUserToken> tblUserTokens { get; set; }
    }
}
