//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEnrollment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEnrollment()
        {
            this.tblPayments = new HashSet<tblPayment>();
        }
    
        public int Id { get; set; }
        public int CourseId { get; set; }
        public string StudentId { get; set; }
        public int Status { get; set; }
        public System.DateTime EnrolledAtUtc { get; set; }
    
        public virtual tblCourse tblCourse { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPayment> tblPayments { get; set; }
    }
}
