//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGrade
    {
        public int Id { get; set; }
        public int AssignmentSubmissionId { get; set; }
        public decimal Score { get; set; }
        public string Feedback { get; set; }
    
        public virtual tblAssignmentSubmission tblAssignmentSubmission { get; set; }
    }
}
