//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOtpToken
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string Purpose { get; set; }
        public string Code { get; set; }
        public System.DateTime ExpiresAtUtc { get; set; }
        public bool IsUsed { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
