//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayment
    {
        public int Id { get; set; }
        public int EnrollmentId { get; set; }
        public decimal Amount { get; set; }
        public int Status { get; set; }
        public string StripeSessionId { get; set; }
        public string StripePaymentIntentId { get; set; }
        public System.DateTime PaidAtUtc { get; set; }
    
        public virtual tblEnrollment tblEnrollment { get; set; }
    }
}
