//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSystemUsageLog
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string RoleName { get; set; }
        public string ActionType { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string Path { get; set; }
        public string HttpMethod { get; set; }
        public int StatusCode { get; set; }
        public string IpAddress { get; set; }
        public string Details { get; set; }
        public System.DateTime LoggedAtUtc { get; set; }
    }
}
